# Generated by Django 5.1.5 on 2025-02-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='employees_count',
            new_name='emp_count',
        ),
    ]
